### ISSUE TITLE
Add more examples

### ISSUE THREAD

**Issue by lorrden** [Deep-Symmetry/bytefield-svg#19]
I am donating the files attached examples which illustrates some network protocols. The ones that adjust the row length to 32 are a bit buggy in the row headers (since they increment by 16 every time).

The examples otherwise include headers for IPv4, IPv6, UDP, TCP, Ethernet frames, and CCSDS space packets.

[protocols.zip](https://github.com/Deep-Symmetry/bytefield-svg/files/4639724/protocols.zip)

**Comment by lorrden** [comment]
All files are dealing with bits, except Ethernet frames which are in bytes.

**Comment by brunchboy** [comment]
Thank you, I will take a look at these when I have some time! Especially the ones where the row headers aren’t working right, I would like to help you get that working the way you want, especially if it might require another change to the documentation or the implementation itself.

Are these going to be in a public repository somewhere? If so I would like to link to them that way so you can get the credit and people can see them in context.

**Comment by lorrden** [comment]
Only the TCP and UDP diagrams change from the default 16 boxes per row. I don't have a repo for these yet, but I may create one.
