### ISSUE TITLE
Add draw-column-headers Function in bytefield-svg

### ISSUE THREAD

**Issue by manipuladordedados** [Deep-Symmetry/bytefield-svg#46]
A new function/helper called draw-column-headers. This would make the header line format resemble the one used in this example: [Packet Diagram Example](http://blockdiag.com/en/nwdiag/packetdiag-examples.html).

**Comment by brunchboy** [comment]
If you would like to write that, you can put it in a file that you include for use in your own diagrams, the way I do for my own shared diagram features in my reverse engineering documentation (here is such a [reusable include file](https://github.com/Deep-Symmetry/dysentery/blob/main/doc/modules/ROOT/examples/dbserver_shared.edn), and here is an [example of using it](https://github.com/Deep-Symmetry/dysentery/blob/65779d6e900068d6a4da1e035669c84481f4fc84/doc/modules/ROOT/pages/track_metadata.adoc?plain=1#L227-L232)).

That’s the whole point of this being an extensible starting point: it can draw any kind of diagram anyone wants, without having to implement everything itself. So this doesn’t belong in bytefield-svg itself, but in an include file for people who want to draw diagrams like that.

**Comment by brunchboy** [comment]
If you would like help writing this, and to explore other ideas, I’d encourage you to join the Deep Symmetry Zulip community and talk about it in the [other projects stream](https://deep-symmetry.zulipchat.com/#narrow/stream/354684-other-projects).

**Comment by brunchboy** [comment]
Also, you would want to call the function something else, because if you look at the [documentation](https://bytefield-svg.deepsymmetry.org/bytefield-svg/1.8.0/funcs.html#draw-column-headers), there already is a `draw-column-headers` function, which draws them the way I like them to look.
