### ISSUE TITLE
Trailing box created by `draw-gap-inline` cannot be styled

### ISSUE THREAD

**Issue by simonarnell** [Deep-Symmetry/bytefield-svg#48]
**Describe the bug**
When using the `draw-gap-inline` function, setting a fill colour has no effect.

**To Reproduce**
The following code will reproduce the non-effect:
```clojure
(defattrs :bg-yellow {:fill "#ffffa0"})
(defattrs :bg-pink {:fill "#ffb0a0"})
(def box-width 200)
(def boxes-per-row 4)
(draw-box "header" :bg-yellow)
(draw-box "variablePayload" [{:borders #{:left :top :bottom}} :bg-pink])
(draw-gap-inline :bg-pink)
(draw-box "trailer" :bg-yellow)
```

**Expected behavior**
Two seamless pink boxes to be created representing the variable length payload structure. Instead a pink and a transparent box are created.

**Screenshots**
<img width="806" alt="image" src="https://github.com/user-attachments/assets/417147d6-cecb-4397-9d27-28a5030a3a52">
**Additional context**
Looking at the source code it seems the second box that holds the gap, isn't actually a `rect` but a series of `line`s, perhaps a solution would be to make these a `polygon` or `path` to allow a fill to be styled onto these structures.
https://github.com/Deep-Symmetry/bytefield-svg/blob/a13edf0e5e31fabba1f798106dfb89a0d5f4f439/src/org/deepsymmetry/bytefield/core.cljs#L586-L634

**Comment by brunchboy** [comment]
You are correct, gaps are not colored. The approach you suggest seems plausible, if you get it working I’d welcome a PR.
